"use client"

import { Button } from "@/components/ui/button"
import { Download } from "lucide-react"
import JSZip from "jszip"
import { saveAs } from "file-saver"
import { toast } from "sonner"

interface DownloadButtonProps {
    html: string
    css: string
    projectName?: string
}

export function DownloadButton({ html, css, projectName = "vibestack-project" }: DownloadButtonProps) {
    const handleDownload = async () => {
        try {
            const zip = new JSZip()

            // Add HTML file
            const fullHtml = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${projectName}</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    ${html}
</body>
</html>`
            zip.file("index.html", fullHtml)

            // Add CSS file
            zip.file("style.css", css)

            // Add README
            zip.file("README.md", `# ${projectName}\n\nGenerated by VibeStack.`)

            const content = await zip.generateAsync({ type: "blob" })
            saveAs(content, `${projectName}.zip`)

            toast.success("Project downloaded!")
        } catch (error) {
            console.error("Download failed:", error)
            toast.error("Failed to download project.")
        }
    }

    return (
        <Button onClick={handleDownload} variant="outline" size="sm">
            <Download className="mr-2 h-4 w-4" />
            <span className="hidden md:inline">Download</span>
        </Button>
    )
}
